package stpa

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ExportV0 writes the records as a stpa-workbench artifact-v0 project, plus the overlay kinds
// and fields proposed in workbench-v0-overlay/. It is a derived view: every value in it is
// computed from the records, including the copies v0 stores redundantly (a UCA's controller,
// a scenario's hazards, the controller/process split of one component, the H1 heading).
func (p *Project) ExportV0(dir string) error {
	if err := os.MkdirAll(filepath.Join(dir, "records"), 0o755); err != nil {
		return err
	}
	pid, _ := p.Manifest["id"].(string)
	title, _ := p.Manifest["title"].(string)
	manifest := map[string]any{
		"schema": "stpa-workbench/project-v0", "id": pid, "title": title, "format_version": 0,
		"description":             "Generated by otel-chdb/stpa/tools export-v0 from the normalized records; do not edit.",
		"method_profiles":         p.Manifest["method_profiles"],
		"content_roots":           []string{"records"},
		"default_document_format": "markdown",
		"views": []map[string]any{{
			"id": "view-" + strings.TrimPrefix(pid, "project-"), "title": "Control structure (all components, v0 form)",
			"file": "diagrams/control-structure.mmd", "source": "generated",
			"derived_from": []string{"records"},
		}},
	}
	if err := writeYAML(filepath.Join(dir, "project.yaml"), manifest); err != nil {
		return err
	}
	hex := func(id string) string { return id[strings.LastIndex(id, "-")+1:] }
	// v0 splits one component into a controller record and a process record (A02); here the
	// split is computed: a component that issues an action gets a controller record, and one
	// that receives an action or sends feedback (or issues nothing) gets a process record.
	ctlID := func(c string) string { return "controller-" + hex(c) }
	procID := func(c string) string { return "process-" + hex(c) }
	// sec and teaming records are v0 scenarios; their exported id keeps the hex, which is
	// unique across kinds (checked), so the rename cannot collide.
	v0id := func(id string) string {
		if r := p.Records[id]; r != nil && (r.Kind == "sec" || r.Kind == "teaming") {
			return "scenario-" + hex(id)
		}
		return id
	}
	v0ids := func(ids []string) []string {
		out := []string{}
		for _, id := range ids {
			out = append(out, v0id(id))
		}
		return out
	}
	type out struct {
		fm   map[string]any
		body string
	}
	var recs []out
	base := func(id, kind, title string, r *Record) map[string]any {
		m := map[string]any{"schema": "stpa-workbench/artifact-v0", "id": id, "kind": kind, "title": clip(title), "state": r.S("state")}
		if l := r.S("label"); l != "" && len(l) <= 40 {
			m["label"] = l
		}
		return m
	}
	for _, id := range p.SortedIDs() {
		r := p.Records[id]
		switch r.Kind {
		case "loss":
			recs = append(recs, out{base(id, "loss", r.S("title"), r), r.S("title")})
		case "hazard":
			m := base(id, "hazard", r.S("title"), r)
			m["system_condition"] = r.S("title")
			m["losses"] = r.L("losses")
			if len(r.L("refines")) > 0 {
				m["refines"] = r.L("refines")
			}
			recs = append(recs, out{m, r.S("title")})
		case "constraint":
			m := base(id, "constraint", r.S("title"), r)
			m["required_condition"] = r.S("title")
			m["hazards"] = r.L("hazards")
			recs = append(recs, out{m, ""})
		case "mechanism":
			m := base(id, "mechanism", r.S("title"), r)
			m["implements"] = r.L("implements")
			m["description"] = r.S("title")
			recs = append(recs, out{m, ""})
		case "component":
			if p.IsController(r) {
				m := base(ctlID(id), "controller", r.S("title"), r)
				m["component_type"] = r.S("component_type")
				recs = append(recs, out{m, "Generated: the controller role of " + id + "."})
			}
			if !p.IsController(r) || p.hasProcessRole(id) {
				m := base(procID(id), "process", r.S("title"), r)
				d := r.S("description")
				if d == "" {
					d = r.S("title")
				}
				m["description"] = d
				recs = append(recs, out{m, "Generated: the controlled-process role of " + id + "."})
			}
		case "action":
			m := base(id, "action", nz(r.S("title"), r.S("label")), r)
			m["from"] = ctlID(r.S("from"))
			m["to"] = procID(r.S("to"))
			m["semantics"] = nz(r.S("title"), r.S("label"))
			recs = append(recs, out{m, ""})
		case "feedback":
			m := base(id, "feedback", nz(r.S("title"), r.S("label")), r)
			m["from"] = procID(r.S("from"))
			m["to"] = ctlID(r.S("to"))
			m["content"] = nz(r.S("title"), r.S("label"))
			recs = append(recs, out{m, ""})
		case "uca":
			a := p.Records[r.S("action")]
			m := base(id, "uca", nz(a.S("title"), a.S("label"))+": "+r.S("context"), r)
			m["controller"] = ctlID(a.S("from"))
			m["action"] = a.ID
			m["category"] = r.S("category")
			m["context"] = r.S("context")
			m["hazards"] = r.L("hazards")
			recs = append(recs, out{m, ""})
		case "scenario":
			m := base(id, "scenario", r.S("title"), r)
			m["hazards"] = p.ScenarioHazards(r)
			m["findings"] = r.L("findings")
			if s := r.S("resolution"); s != "" {
				m["ext"] = map[string]any{"otel-chdb:resolution": s}
			}
			recs = append(recs, out{m, r.S("title")})
		case "sec":
			m := base(v0id(id), "scenario", r.S("title"), r)
			m["hazards"] = r.L("hazards")
			m["findings"] = orEmpty(r.L("findings"))
			m["factors"] = map[string]any{"control": r.S("unsafe"), "environmental": "Adversary: " + r.S("title")}
			m["ext"] = map[string]any{"stpa-sec:mitigation": r.S("mitigation")}
			recs = append(recs, out{m, ""})
		case "teaming":
			m := base(v0id(id), "scenario", r.S("title"), r)
			m["hazards"] = r.L("hazards")
			m["findings"] = []string{}
			m["factors"] = map[string]any{"human": r.S("text")}
			m["ext"] = map[string]any{"stpa-teaming:requirement": r.S("requirement")}
			recs = append(recs, out{m, ""})
		case "requirement":
			m := base(id, "requirement", r.S("title"), r)
			m["statement"] = r.S("title")
			m["priority"] = r.S("priority")
			m["derived_from"] = v0ids(r.L("from"))
			recs = append(recs, out{m, r.S("title")})
		case "incident":
			m := base(id, "incident", r.S("title"), r)
			for _, f := range []string{"batch", "found_by", "why", "fix", "lesson"} {
				m[f] = r.S(f)
			}
			m["hazard_text"] = r.S("hazard")
			m["controller_text"] = r.S("controller")
			var hz []string
			for _, l := range mentionRE.FindAllString(r.S("hazard"), -1) {
				if h := p.ByLabel[l]; h != nil && h.Kind == "hazard" && !contains(hz, h.ID) {
					hz = append(hz, h.ID)
				}
			}
			m["hazards"] = orEmpty(hz)
			recs = append(recs, out{m, r.S("title")})
		}
	}
	for _, o := range recs {
		id := o.fm["id"].(string)
		y, err := yaml.Marshal(o.fm)
		if err != nil {
			return err
		}
		body := "# " + o.fm["title"].(string) + "\n"
		if o.body != "" && o.body != o.fm["title"] {
			body += "\n" + o.body + "\n"
		}
		if err := os.WriteFile(filepath.Join(dir, "records", id+".md"), []byte("---\n"+string(y)+"---\n"+body), 0o644); err != nil {
			return err
		}
	}
	return p.exportV0Diagram(dir)
}

func (p *Project) hasProcessRole(c string) bool {
	for _, a := range p.Of("action") {
		if a.S("to") == c {
			return true
		}
	}
	for _, f := range p.Of("feedback") {
		if f.S("from") == c {
			return true
		}
	}
	return false
}

// exportV0Diagram writes the v0 generated Mermaid (spec §8): a node map and one edge per
// relationship record, labelled with its title, so stpawb's generated-view check can run.
func (p *Project) exportV0Diagram(dir string) error {
	var b strings.Builder
	b.WriteString("%% Generated by otel-chdb/stpa/tools export-v0 from the records; structure is owned by the records.\nflowchart TB\n")
	entries, _ := os.ReadDir(filepath.Join(dir, "records"))
	nodes := map[string]string{}
	var edges []map[string]any
	for _, e := range entries {
		raw, _ := os.ReadFile(filepath.Join(dir, "records", e.Name()))
		s := string(raw)
		end := strings.Index(s[4:], "\n---\n")
		var fm map[string]any
		if err := yaml.Unmarshal([]byte(s[4:4+end+1]), &fm); err != nil {
			return err
		}
		switch fm["kind"] {
		case "controller", "process":
			key := "n" + strings.ReplaceAll(fm["id"].(string), "-", "_")
			nodes[key] = fm["id"].(string)
			fmt.Fprintf(&b, "%%%% node %s = %s\n  %s[\"%s\"]\n", key, fm["id"], key, strings.ReplaceAll(fm["title"].(string), `"`, "'"))
		case "action", "feedback":
			edges = append(edges, fm)
		}
	}
	for _, fm := range edges {
		arrow := "-->"
		if fm["kind"] == "feedback" {
			arrow = "-.->"
		}
		k := func(id any) string { return "n" + strings.ReplaceAll(id.(string), "-", "_") }
		fmt.Fprintf(&b, "  %%%% %s\n  %s %s|\"%s\"| %s\n", fm["id"], k(fm["from"]), arrow, fm["title"], k(fm["to"]))
	}
	if err := os.MkdirAll(filepath.Join(dir, "diagrams"), 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "diagrams", "control-structure.mmd"), []byte(b.String()), 0o644)
}

func clip(s string) string {
	r := []rune(s)
	if len(r) <= 200 {
		return s
	}
	return string(r[:199]) + "…"
}

func nz(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func orEmpty(xs []string) []string {
	if xs == nil {
		return []string{}
	}
	return xs
}

func writeYAML(path string, v any) error {
	b, err := yaml.Marshal(v)
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}
