package stpa

import (
	"fmt"
	"strings"
)

// Mermaid renders the view in the repository's Mermaid convention (STPA.md "Diagram
// conventions"): flowchart TB with ELK, controllers declared before processes in row order,
// every edge written downward from the controller, feedback as `C fbN@<-.->|label| P` with the
// fb class so its only arrowhead is at the controller.
func (L *Layout) Mermaid() string {
	key := func(b *Box) string { return "n" + strings.TrimPrefix(b.Rec.ID[strings.LastIndex(b.Rec.ID, "-"):], "-") }
	var b strings.Builder
	b.WriteString("---\nconfig:\n  layout: elk\n---\nflowchart TB\n")
	fmt.Fprintf(&b, "  %%%% Generated by otel-chdb/stpa/tools from the records (view %s: %s). Do not edit.\n", L.View.ID, L.View.Name)
	node := func(x *Box) {
		label := x.Rec.S("title")
		if len(x.Lines) > 0 {
			label += "<br/>" + x.Rec.S("description")
		}
		if x.Node != nil && x.Node.Controller && L.View.Internals != "" {
			label += fmt.Sprintf("<br/><i>algorithm: %s · process model: %s</i>", plural(len(algoOf(x.Rec)), "rule"), plural(len(pmOf(x.Rec)), "variable"))
		}
		label = strings.ReplaceAll(label, `"`, "#quot;")
		if x.Process {
			fmt.Fprintf(&b, "  %s[(\"%s\")]\n", key(x), label)
		} else {
			fmt.Fprintf(&b, "  %s[\"%s\"]\n", key(x), label)
		}
	}
	for _, x := range L.Boxes {
		if !x.Process {
			node(x)
		}
	}
	for _, x := range L.Boxes {
		if x.Process {
			node(x)
		}
	}
	var fbs []string
	for _, e := range L.Edges {
		if e.Kind == "action" {
			fmt.Fprintf(&b, "  %s -->|%s| %s\n", key(e.From), e.Label, key(e.To))
		} else {
			id := fmt.Sprintf("fb%d", len(fbs)+1)
			fbs = append(fbs, id)
			fmt.Fprintf(&b, "  %s %s@<-.->|%s| %s\n", key(e.To), id, e.Label, key(e.From))
		}
	}
	if len(fbs) > 0 {
		b.WriteString("  classDef fb stroke:#888,marker-end:none\n")
		fmt.Fprintf(&b, "  class %s fb\n", strings.Join(fbs, ","))
	}
	return b.String()
}
