package stpa

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

var ucaCode = map[string]string{
	"not-provided": "NP", "provided": "P", "too-early-too-late-wrong-order": "T", "stopped-too-soon-applied-too-long": "D",
}

// columnValue resolves one table cell. Plain field names show the field (ref lists as their
// labels); the names below are derived values, computed from other records instead of stored.
func (p *Project) columnValue(r *Record, value string) (string, bool) {
	if _, isField := Kinds[r.Kind][value]; isField {
		value = "field:" + value
	}
	switch value {
	case "controller": // UCA: the issuer of its action, by its short name
		if c := p.UCAController(r); c != nil {
			return c.Name(), true
		}
		return "", true
	case "action-name": // UCA: the action's full name
		if a := p.Records[r.S("action")]; a != nil {
			if t := a.S("title"); t != "" {
				return t, true
			}
			return a.S("label"), true
		}
		return "", true
	case "type": // UCA category as its one-letter code
		return ucaCode[r.S("category")], true
	case "mechanisms": // constraint: the mechanisms implementing it (the inverse of implements)
		var names []string
		for _, m := range p.Mechanisms(r) {
			names = append(names, m.S("title"))
		}
		return strings.Join(names, "; "), true
	case "unsafe-with-findings": // SEC: the unsafe action, then the UCAs it is, in parentheses
		s := r.S("unsafe")
		if f := r.L("findings"); len(f) > 0 {
			s += " (" + p.Names(f) + ")"
		}
		return s, true
	case "title-with-priority": // requirement: P0 is the default and unmarked
		s := r.S("title")
		if r.S("priority") != "P0" {
			s += " (" + r.S("priority") + ")"
		}
		return s, true
	case "number": // incident: its CAST row number
		return strings.TrimPrefix(r.S("label"), "CAST-"), true
	case "scenario-hazards":
		return p.Names(p.ScenarioHazards(r)), true
	}
	value = strings.TrimPrefix(value, "field:")
	spec, ok := Kinds[r.Kind][value]
	if !ok {
		if _, common := commonFields[value]; !common {
			return "", false
		}
	}
	if spec.typ == fRefs || spec.typ == fRef {
		return p.Names(r.L(value)), true
	}
	return r.S(value), true
}

func knownColumn(kind, value string) bool {
	derived := map[string][]string{
		"controller": {"uca"}, "action-name": {"uca"}, "type": {"uca"}, "mechanisms": {"constraint", "requirement"},
		"unsafe-with-findings": {"sec"}, "title-with-priority": {"requirement"}, "number": {"incident"},
		"scenario-hazards": {"scenario"},
	}
	if _, ok := Kinds[kind][value]; ok {
		return true
	}
	ks, ok := derived[value]
	return ok && contains(ks, kind)
}

// TableRows returns the records a table shows, in order: natural label order.
func (p *Project) TableRows(t TableSpec) []*Record {
	re := regexp.MustCompile(t.Labels)
	var out []*Record
	for _, r := range p.Of(t.Kind) {
		if t.Labels != "" && !re.MatchString(r.S("label")) {
			continue
		}
		if t.Batch != "" && r.S("batch") != t.Batch {
			continue
		}
		out = append(out, r)
	}
	sort.SliceStable(out, func(i, j int) bool { return NaturalCompare(out[i].S("label"), out[j].S("label")) < 0 })
	return out
}

// TableCells returns the header and the cell strings of a table.
func (p *Project) TableCells(t TableSpec) ([]string, [][]string) {
	var header []string
	for _, c := range t.Columns {
		header = append(header, c.Header)
	}
	var rows [][]string
	for _, r := range p.TableRows(t) {
		var row []string
		for _, c := range t.Columns {
			v, _ := p.columnValue(r, c.Value)
			if v == "" {
				v = c.Empty
			}
			row = append(row, v)
		}
		rows = append(rows, row)
	}
	return header, rows
}

// RenderTable writes a table between generated-section markers, in the repository's table
// style (`| --- |` separators).
func (p *Project) RenderTable(t TableSpec) string {
	header, rows := p.TableCells(t)
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- stpa:begin %s (generated from otel-chdb/stpa/records; edit the records, not this table) -->\n", t.Name)
	b.WriteString("| " + strings.Join(header, " | ") + " |\n")
	b.WriteString("|" + strings.Repeat(" --- |", len(header)) + "\n")
	for _, r := range rows {
		b.WriteString("| " + strings.Join(r, " | ") + " |\n")
	}
	fmt.Fprintf(&b, "<!-- stpa:end %s -->\n", t.Name)
	return b.String()
}

// RenderTables renders every table of a tables view as one Markdown file.
func (p *Project) RenderTables(v *View) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by otel-chdb/stpa/tools (stpa render). Do not edit: edit the records. -->\n")
	for _, t := range v.Tables {
		b.WriteString("\n")
		b.WriteString(p.RenderTable(t))
	}
	return b.String()
}
