#!/bin/bash
# Deploy the edge (a deploy/overlays/{EDGE}-eks-{VARIANT} overlay, with this
# run's cluster, bucket, prefix, images and role) and the validation side
# (ClickHouse, the consumer, GC, the toolbox) into the EKS cluster.
#
#   RUN=v1 BUCKET=... REGION=us-east-1 [EDGE=rust|go VARIANT=irsa|pod-identity OVERLAY=rust-eks-irsa-routing \
#     CH_IMAGE=clickhouse/clickhouse-server:26.10 WORKERS=2] eks/deploy.sh [edge|central|all]
#
# The overlay is not copied: $STATE/overlay-$EDGE-$VARIANT/kustomization.yaml
# takes the repository's overlay as its resource and merges the run's values
# into its edge-target ConfigMap, so what runs is what deploy/ ships.
# TARGET=nutanix (nutanix.md §5): OVERLAY defaults to $EDGE-nutanix, the run's
# endpoint, bucket, CA (CA_BUNDLE, merged into the ConfigMap nutanix-objects-ca)
# and the Secret nutanix-objects-credentials from NX_KEY/NX_SECRET; no IAM.
# The central half is EKS-only (on a Nutanix site run ClickHouse and consume
# on a VM: nutanix.md §5).
# Switching VARIANT: the IRSA annotation and the Pod Identity association are
# exclusive (the web-identity variables win in both clients' chains), so this
# removes the one it does not want, then restarts the publishers.
# shellcheck source=../lib.sh
. "$(dirname "$0")/../lib.sh"
need kubectl aws python3
: "${BUCKET:?}"
REGION=${REGION:-us-east-1}
CLUSTER=${CLUSTER:-otel-val-$RUN}
EDGE=${EDGE:-rust}
VARIANT=${VARIANT:-irsa}
CH_IMAGE=${CH_IMAGE:-clickhouse/clickhouse-server:26.10}
WORKERS=${WORKERS:-2}
DB=${DB:-eks_edge}
KUSTOMIZE=${KUSTOMIZE:-kustomize}
WHAT=${1:-all}
export KUBECONFIG=${KUBECONFIG:-$STATE/kubeconfig}
TARGET=${TARGET:-eks}
if [ "$TARGET" = eks ]; then
  # shellcheck source=/dev/null
  . "$STATE/iam.env" || die "run eks/iam.sh first"
else
  : "${NX_ENDPOINT:?}" "${CA_BUNDLE:?}" "${NX_KEY:?}" "${NX_SECRET:?}"
  [ "$WHAT" = edge ] || die "TARGET=nutanix: deploy.sh edge only (central on a VM: nutanix.md §5)"
fi
# shellcheck source=/dev/null
. "$STATE/images.env" || die "run eks/images.sh first"
S3_BASE=s3://$BUCKET/$VPREFIX/edge
[ "$TARGET" = nutanix ] && S3_BASE=$NX_ENDPOINT/$BUCKET/$VPREFIX/edge
case "$EDGE" in rust) SA=otap-publisher; STS=otap-publisher;; go) SA=otelcol-publisher; STS=otelcol-publisher;; *) die "EDGE rust|go";; esac
case "$VARIANT" in irsa|pod-identity) ;; *) die "VARIANT irsa|pod-identity";; esac

if [ "$WHAT" = edge ] || [ "$WHAT" = all ]; then
  if [ "$TARGET" = nutanix ]; then OVERLAY=${OVERLAY:-$EDGE-nutanix}; else OVERLAY=${OVERLAY:-$EDGE-eks-$VARIANT}; fi
  O=$STATE/overlay-$OVERLAY
  mkdir -p "$O"
  # kustomize takes a relative path only.
  REL=$(python3 -c 'import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$DEPLOY_DIR/overlays/$OVERLAY" "$O")
  {
    cat <<EOF
# Generated by validation/eks/deploy.sh for run $RUN: the repository's overlay
# plus this run's values. Do not edit; rerun deploy.sh.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-edge
resources:
  - $REL
configMapGenerator:
  - name: edge-target
    behavior: merge
    literals:
      - CLUSTER=$CLUSTER
      - S3_BUCKET=$BUCKET
      - S3_REGION=$REGION
      - S3_BASE=$S3_BASE
$( [ "$TARGET" = nutanix ] && printf '      - S3_ENDPOINT=%s\n  - name: nutanix-objects-ca\n    behavior: merge\n    files:\n      - ca.pem=ca.pem\n' "$NX_ENDPOINT" )
images:
  - {name: REGISTRY/otap-s3pq, newName: ${IMG_OTAP%:*}, newTag: ${IMG_OTAP##*:}}
  - {name: REGISTRY/otelcol-deploy, newName: ${IMG_OTELCOL%:*}, newTag: ${IMG_OTELCOL##*:}}
  - {name: REGISTRY/otelcol-s3pq, newName: ${IMG_GOPUB%:*}, newTag: ${IMG_GOPUB##*:}}
  - {name: REGISTRY/otelcol-deploy-lbpatched, newName: ${IMG_GATEWAY%:*}, newTag: ${IMG_GATEWAY##*:}}
EOF
    if [ "$TARGET" = eks ] && [ "$VARIANT" = irsa ]; then
      cat <<EOF
patches:
  - target: {kind: ServiceAccount, name: $SA}
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: $R_EDGE
EOF
    fi
  } > "$O/kustomization.yaml"
  [ "$TARGET" = nutanix ] && cp -f "$CA_BUNDLE" "$O/ca.pem"
  "$KUSTOMIZE" build --load-restrictor LoadRestrictionsNone "$O" > "$O/rendered.yaml" || die "kustomize build $O"
  grep -q 'CHANGE-ME' "$O/rendered.yaml" && die "a CHANGE-ME is left in $O/rendered.yaml"
  if [ "$TARGET" = nutanix ]; then
    kubectl get ns otel-edge > /dev/null 2>&1 || { kubectl create ns otel-edge > /dev/null; created k8s-namespace otel-edge; }
    kubectl -n otel-edge create secret generic nutanix-objects-credentials --from-literal=AWS_ACCESS_KEY_ID="$NX_KEY" \
      --from-literal=AWS_SECRET_ACCESS_KEY="$NX_SECRET" --dry-run=client -o yaml | kubectl apply -f - > /dev/null
  elif [ "$VARIANT" = pod-identity ]; then
    kubectl -n otel-edge annotate sa "$SA" eks.amazonaws.com/role-arn- > /dev/null 2>&1 || true
    if [ -z "$(aws eks list-pod-identity-associations --region "$REGION" --cluster-name "$CLUSTER" --namespace otel-edge \
          --service-account "$SA" --query 'associations[0].associationId' --output text | grep -v None)" ]; then
      id=$(aws eks create-pod-identity-association --region "$REGION" --cluster-name "$CLUSTER" --namespace otel-edge \
        --service-account "$SA" --role-arn "$R_PODID" --query association.associationId --output text) || die "association"
      created pod-identity-association "$id" "$CLUSTER"
    fi
  else
    for id in $(aws eks list-pod-identity-associations --region "$REGION" --cluster-name "$CLUSTER" --namespace otel-edge \
        --service-account "$SA" --query 'associations[].associationId' --output text | tr '\t' '\n' | grep -v '^None$'); do
      was_created pod-identity-association "$id" || die "a Pod Identity association $id this run did not make shadows IRSA: remove it by hand"
      aws eks delete-pod-identity-association --region "$REGION" --cluster-name "$CLUSTER" --association-id "$id" > /dev/null
    done
  fi
  kubectl get ns otel-edge > /dev/null 2>&1 || created k8s-namespace otel-edge
  kubectl apply -f "$O/rendered.yaml"
  created k8s-manifest "$O/rendered.yaml"
  kubectl -n otel-edge rollout restart "sts/$STS" > /dev/null
  kubectl -n otel-edge rollout status "sts/$STS" --timeout=10m || die "publishers not ready (kubectl -n otel-edge describe pod)"
  kubectl -n otel-edge rollout status ds/otel-agent --timeout=10m || die "agents not ready"
  if kubectl -n otel-edge get deploy otel-gateway > /dev/null 2>&1; then
    # components/routing switches the publishers' serviceName: a rollout restart puts the ring hostnames in place (k8s-sim.md §7)
    kubectl -n otel-edge rollout status deploy/otel-gateway --timeout=10m || die "gateways not ready"
  fi
  # Which credential path did the webhook give the publisher? (IRSA: AWS_ROLE_ARN; Pod Identity: the container URI.)
  env=$(kubectl -n otel-edge exec "$STS-0" -c "$(kubectl -n otel-edge get pod "$STS-0" -o jsonpath='{.spec.containers[0].name}')" -- env 2> /dev/null \
    | grep -E '^AWS_(ROLE_ARN|WEB_IDENTITY_TOKEN_FILE|CONTAINER_CREDENTIALS_FULL_URI|CONTAINER_AUTHORIZATION_TOKEN_FILE|EC2_METADATA_DISABLED)=' | sort | tr '\n' ' ')
  result "deploy.$OVERLAY.env" "${env:-(exec not possible: check the pod spec)}"
fi

if [ "$WHAT" = central ] || [ "$WHAT" = all ]; then
  kubectl get ns otel-validate > /dev/null 2>&1 || { kubectl create ns otel-validate > /dev/null; created k8s-namespace otel-validate; }
  # deploy/base's NetworkPolicy opens the publishers' admin/metrics port to a namespace with this label only.
  kubectl label ns otel-validate otel-edge/monitoring=true --overwrite > /dev/null
  render "$VALIDATION_DIR/eks/manifests/clickhouse.yaml.tmpl" "$STATE/clickhouse.yaml" CH_IMAGE="$CH_IMAGE"
  render "$VALIDATION_DIR/eks/manifests/consumer.yaml.tmpl" "$STATE/consumer.yaml" IMG_TOOLBOX="$IMG_TOOLBOX" \
    S3_BASE="$S3_BASE" DB="$DB" WORKERS="$WORKERS" REGION="$REGION"
  kubectl apply -f "$STATE/clickhouse.yaml" && created k8s-manifest "$STATE/clickhouse.yaml"
  kubectl -n otel-validate rollout status sts/clickhouse --timeout=10m || die "clickhouse not ready"
  kubectl apply -f "$STATE/consumer.yaml" && created k8s-manifest "$STATE/consumer.yaml"
  kubectl -n otel-validate rollout status deploy/consume --timeout=5m
  kubectl -n otel-validate wait --for=condition=Ready pod/toolbox --timeout=5m
  result central.clickhouse "$(kubectl -n otel-validate exec toolbox -- curl -s http://clickhouse.otel-validate:8123/ --data-binary 'SELECT version()')"
fi
